project:
  type: website
  output-dir: docs

website:
  title: "Curs zero d’Informàtica"
  navbar:
    left:
      - href: index.qmd
        text: Home
  

format:
  html:
    theme:
      - cosmo
    toc: true


